version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "endondemevacuno-iot"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
